import { STATUS_LABEL } from "../../core/constants/status-labels.js";

export const TASK_STATUS = {
    PENDING: STATUS_LABEL.PENDING,
    RUNNING: STATUS_LABEL.RUNNING,
    COMPLETED: STATUS_LABEL.COMPLETED,
    FAILED: STATUS_LABEL.FAILED,
    ERROR: STATUS_LABEL.ERROR,
    TIMEOUT: STATUS_LABEL.TIMEOUT,
    CANCELLED: STATUS_LABEL.CANCELLED,
} as const;
